### ISSUE TITLE
does not implement openfeature.FeatureProvider

### ISSUE THREAD

**Issue by rittneje** [rollout/cloudbees-openfeature-provider-go#6]
This library does not, nor has it ever implemented the `openfeature.FeatureProvider`, rendering the entire library useless.

1. Fix go.mod to use the latest version of openfeature (v1.3.0 presently).
2. Fix your `cloudbees.Provider` struct to actually implement `openfeature.FeatureProvider`.
3. Add a `var _ openfeature.FeatureProvider = (*cloudbees.Provider)(nil)` line somewhere to prove you actually implement the interface.
4. Retract all prior versions of this library since they are broken.

**Comment by pawoolley** [comment]
Latest version ([tag 1.8.0](https://github.com/rollout/cloudbees-openfeature-provider-go/tree/v1.8.0)) now properly implements the `FeatureProvider` interface, with a [test](https://github.com/rollout/cloudbees-openfeature-provider-go/blob/v1.8.0/pkg/cloudbees/provider_test.go#L688) to check.
